
-- SLZB-Erfolge v3 - Basisschema, Rollen, RLS und Statusworkflow
create extension if not exists pgcrypto;
create type public.app_role as enum ('trainer','redaktion','oea','datenschutz','admin');
create type public.achievement_status as enum ('Entwurf','Unvollständig','Eingereicht','Rückfrage an Melder','Datenprüfung','Dublettenverdacht','Einwilligungsprüfung','Redaktion','Freigabe Öffentlichkeitsarbeit','Teilweise freigegeben','Freigegeben','Veröffentlicht','Archiviert','Wegen Einwilligung gesperrt','Widerrufen','Zur Löschung vorgemerkt','Gelöscht/Anonymisiert');
create table public.profiles(user_id uuid primary key references auth.users(id) on delete cascade,username text not null unique,display_name text not null,role app_role not null default 'trainer',active boolean not null default true,created_at timestamptz not null default now());
create table public.sports(id text primary key,name text not null unique,code text not null unique,category text,active boolean not null default true,disciplines text[] not null default '{}');
create table public.competitions(id text primary key default ('WB-'||substr(gen_random_uuid()::text,1,8)),name text not null,organizer text,location text,starts_on date,ends_on date,level text,sport_id text references public.sports(id));
create table public.students(id text primary key default ('SLZB-'||substr(gen_random_uuid()::text,1,8)),student_number text unique,first_name text not null,last_name text not null,display_name text not null,class_name text,group_name text,sport_id text references public.sports(id),active boolean not null default true,created_at timestamptz not null default now());
create table public.consents(id uuid primary key default gen_random_uuid(),student_id text not null unique references public.students(id) on delete cascade,photo boolean not null default false,print boolean not null default false,homepage boolean not null default false,digital_signage boolean not null default false,social_media boolean not null default false,single_portrayal boolean not null default false,show_class boolean not null default false,valid_until date,revoked_at timestamptz,updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.teams(id text primary key default ('TM-'||substr(gen_random_uuid()::text,1,8)),name text not null,sport_id text references public.sports(id),category text,school_year text,active boolean not null default true);
create sequence public.achievement_no_seq;
create table public.achievements(id uuid primary key default gen_random_uuid(),achievement_no text not null unique default ('ERF-'||lpad(nextval('public.achievement_no_seq')::text,8,'0')),report_type text not null,title text not null,sport_id text references public.sports(id),discipline text,competition_id text references public.competitions(id),event_date date not null,location text,level text,placement integer check(placement is null or placement>=1),medal text,result_value numeric,result_unit text,result_text text,short_info text,source_url text,status achievement_status not null default 'Entwurf',reporter_id uuid not null references auth.users(id),reporter_name text not null,submitted_at timestamptz not null default now(),consent_checked boolean not null default false,article_text text,ai_draft text,duplicate_flag boolean not null default false,duplicate_note text,version integer not null default 1,updated_at timestamptz not null default now());
create table public.achievement_participants(id uuid primary key default gen_random_uuid(),achievement_id uuid not null references public.achievements(id) on delete cascade,student_id text not null references public.students(id),participant_role text not null default 'Athlet',consent_status text not null default 'Nicht geprüft',unique(achievement_id,student_id));
create table public.achievement_status_history(id bigint generated always as identity primary key,achievement_id uuid not null references public.achievements(id) on delete cascade,old_status achievement_status,new_status achievement_status not null,changed_at timestamptz not null default now(),changed_by uuid references auth.users(id),changed_by_name text,comment text);
create table public.achievement_media(id uuid primary key default gen_random_uuid(),achievement_id uuid not null references public.achievements(id) on delete cascade,storage_path text not null unique,original_name text not null,mime_type text not null,creator text not null,source text not null,caption text,alt_text text,created_at timestamptz not null default now());
create table public.import_jobs(id uuid primary key default gen_random_uuid(),source_filename text,total_rows integer not null default 0,success_rows integer not null default 0,error_rows integer not null default 0,status text not null,error_log text,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.audit_log(id bigint generated always as identity primary key,actor_id uuid,action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}',created_at timestamptz not null default now());

create or replace function public.current_user_role() returns app_role language sql stable security definer set search_path=public as $$ select role from profiles where user_id=auth.uid() and active $$;
create or replace function public.email_for_username(p_username text) returns text language sql security definer set search_path=public,auth as $$ select u.email from auth.users u join public.profiles p on p.user_id=u.id where lower(p.username)=lower(p_username) and p.active limit 1 $$;
revoke all on function public.email_for_username(text) from public; grant execute on function public.email_for_username(text) to anon,authenticated;

create or replace function public.status_transition_allowed(p_role app_role,p_old achievement_status,p_new achievement_status) returns boolean language sql immutable as $$ select case p_role
 when 'admin' then true
 when 'trainer' then (p_old,p_new) in (('Entwurf','Eingereicht'),('Rückfrage an Melder','Eingereicht'))
 when 'redaktion' then (p_old,p_new) in (('Eingereicht','Datenprüfung'),('Eingereicht','Rückfrage an Melder'),('Eingereicht','Unvollständig'),('Eingereicht','Dublettenverdacht'),('Datenprüfung','Einwilligungsprüfung'),('Datenprüfung','Redaktion'),('Datenprüfung','Rückfrage an Melder'),('Einwilligungsprüfung','Redaktion'),('Einwilligungsprüfung','Wegen Einwilligung gesperrt'),('Dublettenverdacht','Redaktion'),('Dublettenverdacht','Gelöscht/Anonymisiert'),('Redaktion','Freigabe Öffentlichkeitsarbeit'),('Redaktion','Rückfrage an Melder'),('Unvollständig','Rückfrage an Melder'),('Unvollständig','Redaktion'))
 when 'oea' then (p_old,p_new) in (('Freigabe Öffentlichkeitsarbeit','Freigegeben'),('Freigabe Öffentlichkeitsarbeit','Teilweise freigegeben'),('Freigabe Öffentlichkeitsarbeit','Redaktion'),('Freigegeben','Veröffentlicht'),('Freigegeben','Archiviert'))
 when 'datenschutz' then (p_old,p_new) in (('Einwilligungsprüfung','Redaktion'),('Einwilligungsprüfung','Wegen Einwilligung gesperrt'),('Wegen Einwilligung gesperrt','Einwilligungsprüfung'),('Wegen Einwilligung gesperrt','Zur Löschung vorgemerkt')) else false end $$;
create or replace function public.change_achievement_status(p_achievement_id uuid,p_new_status achievement_status,p_comment text default '') returns void language plpgsql security definer set search_path=public as $$ declare v_old achievement_status; v_role app_role; v_name text; begin select status into v_old from achievements where id=p_achievement_id for update; if not found then raise exception 'Meldung nicht gefunden'; end if; select role,display_name into v_role,v_name from profiles where user_id=auth.uid() and active; if not status_transition_allowed(v_role,v_old,p_new_status) then raise exception 'Statuswechsel nicht erlaubt'; end if; update achievements set status=p_new_status,updated_at=now(),version=version+1 where id=p_achievement_id; insert into achievement_status_history(achievement_id,old_status,new_status,changed_by,changed_by_name,comment) values(p_achievement_id,v_old,p_new_status,auth.uid(),v_name,p_comment); insert into audit_log(actor_id,action,entity_type,entity_id,details) values(auth.uid(),'status_change','achievement',p_achievement_id::text,jsonb_build_object('old',v_old,'new',p_new_status)); end $$;

alter table profiles enable row level security; alter table sports enable row level security; alter table competitions enable row level security; alter table students enable row level security; alter table consents enable row level security; alter table teams enable row level security; alter table achievements enable row level security; alter table achievement_participants enable row level security; alter table achievement_status_history enable row level security; alter table achievement_media enable row level security; alter table import_jobs enable row level security; alter table audit_log enable row level security;
create policy profile_self_or_admin on profiles for select to authenticated using(user_id=auth.uid() or current_user_role()='admin');
create policy reference_read on sports for select to authenticated using(true); create policy competition_read on competitions for select to authenticated using(true); create policy teams_read on teams for select to authenticated using(true);
create policy staff_students_read on students for select to authenticated using(current_user_role() in ('trainer','redaktion','datenschutz','admin'));
create policy privacy_consents_read on consents for select to authenticated using(current_user_role() in ('redaktion','datenschutz','admin'));
create policy achievements_read on achievements for select to authenticated using(reporter_id=auth.uid() or current_user_role() in ('redaktion','oea','datenschutz','admin'));
create policy achievements_insert on achievements for insert to authenticated with check(reporter_id=auth.uid() and current_user_role() in ('trainer','redaktion','admin'));
create policy achievements_update on achievements for update to authenticated using(reporter_id=auth.uid() or current_user_role() in ('redaktion','admin')) with check(reporter_id=auth.uid() or current_user_role() in ('redaktion','admin'));
create policy participants_read on achievement_participants for select to authenticated using(exists(select 1 from achievements a where a.id=achievement_id and (a.reporter_id=auth.uid() or current_user_role() in ('redaktion','oea','datenschutz','admin'))));
create policy participants_insert on achievement_participants for insert to authenticated with check(exists(select 1 from achievements a where a.id=achievement_id and a.reporter_id=auth.uid()));
create policy history_read on achievement_status_history for select to authenticated using(exists(select 1 from achievements a where a.id=achievement_id and (a.reporter_id=auth.uid() or current_user_role() in ('redaktion','oea','datenschutz','admin'))));
create policy media_read on achievement_media for select to authenticated using(exists(select 1 from achievements a where a.id=achievement_id and (a.reporter_id=auth.uid() or current_user_role() in ('redaktion','oea','datenschutz','admin'))));
create policy imports_own on import_jobs for select to authenticated using(created_by=auth.uid() or current_user_role() in ('redaktion','admin'));
create policy audit_admin on audit_log for select to authenticated using(current_user_role()='admin');

insert into storage.buckets(id,name,public) values('achievement-media','achievement-media',false) on conflict(id) do nothing;
create policy media_objects_select on storage.objects for select to authenticated using(bucket_id='achievement-media');
create policy media_objects_insert on storage.objects for insert to authenticated with check(bucket_id='achievement-media' and current_user_role() in ('trainer','redaktion','admin'));
